apiVersion: v1
kind: Namespace
metadata:
  name: policies-appset
spec: {}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  namespace: policies-appset
  name: default
spec:
  clusterSet: default
