---  
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: policies-appset
  namespace: policies-appset
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: policies-appset
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: policies-appset-placement 
    namespace: policies-appset
