apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blue-sre-group
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - blueteam
  resources:
  - managedclustersets
  verbs:
  - get
  - update
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - default
  resources:
  - managedclustersets/join
  verbs:
  - create
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - default
  resources:
  - managedclustersets/bind
  verbs:
  - create
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - create
- apiGroups:
  - register.open-cluster-management.io
  resources:
  - managedclusters/accept
  verbs:
  - update
- apiGroups:
  - clusterview.open-cluster-management.io
  resources:
  - managedclustersets
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - pods
  - services
  - namespaces
  - nodes
  verbs: 
  - create
  - get
  - update
  - list
  - watch
  - patch
- apiGroups: 
  - apps
  resources: 
  - deployment
  verbs: 
  - create
  - get
  - update
  - list 
  - delete
  - watch 
  - patch
- apiGroups: [""] #specifies core api groups
  resources: 
  - resourcequotas
  - limitranges
  verbs: 
  - create  
- apiGroups:  
  - argoproj.io 
  resources: 
  - applications
  - applicationsets   
  verbs: 
  - create
  - get
  - update
  - list 
  - delete
  - watch 
  - patch  
- apiGroups:
  - rbac.authorization.k8s.io
  resources: 
  - clusterroles
  - clusterrolebindings
  verbs:
  - get 
  - list 
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - placements
  - placementrules
  - placementbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.open-cluster-management.io/v1
  resources:
  - applications
  - channels
  - subscriptions
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blue-sre-rolebinding
subjects:
  - kind: Group
    name: blue-sre-group
roleRef:
  kind: ClusterRole
  name: blue-sre-group
  apiGroup: rbac.authorization.k8s.io
