apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:managedclusterset:admin:blueteam
  namespace: blueteam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:managedclusterset:admin:blueteam
subjects:
- kind: Group
  name: blue-sre-group
