apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-placementrules
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: disallow-placementrules
    match:
      resources:
        kinds:
        - apps.open-cluster-management.io/*/PlacementRules
      subjects:
      - kind: Group
        name: red-sre-group
    validate:
      message: "Using Placement Rules not allowed"
      deny: {}          
 
