---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-managedclustersetbinding-blue-sre-group
  annotations:
    policies.kyverno.io/title: Add ArgoCD Rolebinding
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: ClusterRoleBinding
    policies.kyverno.io/description: >-
      When a user from Team1 creates a NS a ClusterRoleBinding gets created so
      it can access ArgoCD.
spec:
  background: false
  rules:
  - name: generate-clusterrolebinding-bluegroup
    match:
      any:
      - resources:
          kinds:
            - Namespace
        subjects:
        - kind: Group
          name: "blue-sre-group"
    generate:
      apiVersion: cluster.open-cluster-management.io/v1beta1
      kind: ManagedClusterSetBinding
      name: blueteam
      namespace: {{request.object.metadata.name}}
      synchronize: true
      data:
        spec:
          clusterSet: blueteam
          

