---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-managedclustersetbinding-blue-sre-group
  annotations:
    policies.kyverno.io/title: Add ArgoCD Rolebinding
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/subject: ClusterRoleBinding
    policies.kyverno.io/description: >-
      When a user from Team1 creates a NS a ClusterRoleBinding gets created so
      it can access ArgoCD.
spec:
  background: false
  rules:
  - name: generate-placement-blue
    match:
      any:
      - resources:
          kinds:
            - Namespace
        subjects:
        - kind: Group
          name: "blue-sre-group"
    generate:
      apiVersion: cluster.open-cluster-management.io/v1beta1
      kind: Placement
      metadata:
        name: blueteam
        namespace: {{request.object.metadata.name}}
      spec:
        predicates:
        - requiredClusterSelector:
            labelSelector:
              matchLabels:
                cluster.open-cluster-management.io/placement: blueplacement
          

