
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-bootstrap
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    gitops.example.com/component: bootstrap
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: security
  source:
    path: gitops/cluster/config/base/security/bootstrap
    repoURL: 'https://https://github.com/ch-stark/okd-lab.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m  
