---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: bluetest
---
apiVersion: v1
kind: Namespace
metadata:
  name: redteam
---

apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno-policies
---
apiVersion: v1
kind: Namespace
metadata:
  name: policies-appset
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops  
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops-group
  namespace: openshift-gitops-operator
spec:
  targetNamespaces: []
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: 'openshift-gitops, testroles, test, kyverno, kyverno-policies, policies, policiesappset'


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fulldemo
  namespace: openshift-gitops
spec:
  destination:
    namespace: fulldemo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rbacmultitenancydemo
    repoURL: github.com:ch-stark/gitops-rbac-example
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true        

