apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-generator-blog
  namespace: policies-appset
spec:
  destination:
    namespace: policies-appset
    server: https://kubernetes.default.svc
  project: policies-project
  source:
    path: policygenerator/kustomize
    repoURL: https://github.com/ch-stark/gitops-rbac-example.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
