apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-generator-rbac-setup
placementBindingDefaults:
  name: binding-example
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  remediationAction: enforce
  severity: medium
  standards:
    - rbac
policies:
- name: policy-rbac-setup
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: output
