apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:managedclusterset:admin:default
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - default
  resources:
  - managedclustersets
  verbs:
  - get
  - update
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - default
  resources:
  - managedclustersets/join
  verbs:
  - create
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - default
  resources:
  - managedclustersets/bind
  verbs:
  - create
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - create
- apiGroups:
  - register.open-cluster-management.io
  resources:
  - managedclusters/accept
  verbs:
  - update
- apiGroups:
  - clusterview.open-cluster-management.io
  resources:
  - managedclustersets
  verbs:
  - get
  - list
  - watch

