apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:admin:redcluster1
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - redcluster1
  resources:
  - managedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterview.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
