apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:admin:redclusterset
labels:
    cluster.open-cluster-management.io/clusterset: redteam
    cluster.open-cluster-management.io/role: admin
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - redteam
  resources:
  - managedclustersets
  verbs:
  - get
  - update
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - redteam
  resources:
  - managedclustersets/join
  verbs:
  - create
- apiGroups:
  - cluster.open-cluster-management.io
  resourceNames:
  - redteam
  resources:
  - managedclustersets/bind
  verbs:
  - create
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - create
- apiGroups:
  - register.open-cluster-management.io
  resources:
  - managedclusters/accept
  verbs:
  - update
- apiGroups:
  - clusterview.open-cluster-management.io
  resources:
  - managedclustersets
  verbs:
  - get
  - list
  - watch
