apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blueteam-project
  namespace: blueteam
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  roles:
   data:
    policy.csv: |
      g, acm-sre-group, role:admin
      g, acm-viewer-group, role:readonly
      g, blue-sre-group, role:admin
      g, blue-viewer-group, role:readonly
    policy.default: role:''
    scopes: '[groups]'
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

