apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: policies-project
  namespace: policies-appset
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  namespaceResourceBlacklist:
    - group: 'apps.open-cluster-management.io'
      kind: PlacementRule
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'


