apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redteam-project
  namespace: redteam
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  roles:
   data:
    policy.csv: |
      g, acm-sre-group, role:admin
      g, acm-viewer-group, role:readonly
      g, red-sre-group, role:admin
      g, red-viewer-group, role:readonly
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'


