apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redteam
  namespace: redteam
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  namespaceResourceBlacklist:
    - group: 'open-cluster-management.io'
      kind: PlacementRule
  destinations:
    - namespace: redteam-*
      server: '*'
  roles:
    - groups:
        - red-sre-group
      name: red-sre-group
      policies:
        - 'p, proj:redteam:red-sre-group-admin, applications, *, redteam/*, allow'
    - groups:
        - red-viewer-group
      name: red-viewer-group
      policies:
        - 'p, proj:redteam:red-viewer-group, applications, get, redteam/*, allow'
        - 'p, proj:redteam:red-viewer-group, applications, sync, redteam/*, allow'
        - 'p, proj:redteam:red-viewer-group, applications, action, redteam/*, allow'
        - 'p, proj:redteam:red-viewer-group, applications, delete, redteam/*, allow'
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'


