---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
<<<<<<< HEAD
  name: redteamviewer
=======
  name: gitopsclusters
>>>>>>> adc19cdd7ff801045f9c80991e007e97b80f2065
  namespace: openshift-gitops
spec:
  destination:
    namespace: fulldemo
    server: https://kubernetes.default.svc
  project: default
  source:
<<<<<<< HEAD
    path: rbacmultitenancydemo/redteamviewer
=======
    path: rbacmultitenancydemo/gitopsclusters
>>>>>>> adc19cdd7ff801045f9c80991e007e97b80f2065
    repoURL: https://github.com/ch-stark/gitops-rbac-example.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
<<<<<<< HEAD
      prune: true        
=======
      prune: true
>>>>>>> adc19cdd7ff801045f9c80991e007e97b80f2065
