---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: openshift-gitops
spec:
  destination:
    namespace: fulldemo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rbacmultitenancydemo/kyverno/overlay/policies
    repoURL: https://github.com/ch-stark/gitops-rbac-example.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
     - Validate=false
     - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true        
