---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshiftsetup
  namespace: openshift-gitops
spec:
  destination:
    namespace: fulldemo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rbacmultitenancydemo/openshiftsetup
    repoURL: https://github.com/ch-stark/gitops-rbac-example.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: config.openshift.io
      kind: OAuth
      jqPathExpressions:
        - '.spec.identityProviders[] | select(.name != "my_htpasswd_provider")'
