---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-upgrade-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: fulldemo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy
    repoURL: https://github.com/openshift/managed-upgrade-operator
    targetRevision: HEAD
  ignoreDifferences:
  - kind: "Namespace"  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    automated:
      selfHeal: true
      prune: true    

