---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-virtualization
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-cnv
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rbacmultitenancydemo/virtualization
    repoURL: https://github.com/ch-stark/gitops-rbac-example.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
