apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: policies
  namespace: policies
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'