apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: dev1
  namespace: dev1
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
