apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: defaultplacement
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: name
          operator: "In"
          values:
          - local-cluster
