apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blue-mobile-application-set
  namespace: blueteam
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: blue-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: mobileapp-{{name}}
    spec:
      project: blueteam-project
      source:
        repoURL: https://github.com/rokej/BlueApplications.git
        targetRevision: main
        path: mobileApplication
      destination:
        namespace: bluemobileapp
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
