apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno-policies
  namespace: kyverno-policies
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchExpressions:
          - {key: local-cluster, operator: NotIn, values: ['true']}
        requeueAfterSeconds: 180
  template:
    metadata:
      name: kyverno-policies-{{name}}
    spec:
      project: kyverno-policies
      source:
        path: rbacmultitenancydemo/kyverno/overlay/policies
        repoURL: https://github.com/ch-stark/gitops-rbac-example.git
        targetRevision: HEAD
      destination:
        namespace: kyverno
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
