apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno-policies
  namespace: kyverno-policies
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: NotIn
              value: true
        requeueAfterSeconds: 180
  template:
    metadata:
      name: kyverno-policies-{{name}}
    spec:
      project: kyverno-policies
      source:
        path: kyverno
        repoURL: https://github.com/ch-stark/gitops-rbac-example.git
        targetRevision: HEAD
      destination:
        namespace: kyverno
        server: "{{server}}"
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
      automated:
        selfHeal: true
