---  
apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: kyverno-appset
  namespace: kyverno
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: kyverno
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: application-set-kyveno
    namespace: kyverno
