apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: red-sre-group
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces", "nodes"]
    verbs: ["create", "get", "update", "list", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployment"]
    verbs: ["create", "get", "update", "list", "delete", "watch", "patch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: red-sre-rolebinding
subjects:
  - kind: Group
    name: red-sre-group
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: red-sre-group
  apiGroup: rbac.authorization.k8s.io
