apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: quota-limit-cluster-role
rules:
- apiGroups: [""] #specifies core api groups
  resources: ["resourcequotas", "limitranges"]
  verbs: ["create"]

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows Service Account to create resource quotas and limit ranges in any namespace.
kind: ClusterRoleBinding
metadata:
  name: create-quota-limit-global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quota-limit-cluster-role # Name of cluster role to be referenced
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-argocd-application-controller
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: [""]
  resources: ["services"]
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
