
apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  htpasswd: Ymx1ZXNyZTE6JDJ5JDA1JEViNVVqVkp3STRqcGtic0ZvUHlBTXVjWFF6UTdlL0E5U3R5QkdvbTFOWjd4L3I5STVQSTBTCmJsdWVzcmUyOiQyeSQwNSRlSC5IS2NqUlZ5VC9uVlVSVjlRYXUucUo4MmhXUzR5S3ZITEg4ZnNJdHZPbE9VandBOFYvSwpyZWRzcmUxOiQyeSQwNSQ2VHR5NktpRmpuL3NSVlhOb1BlbWdlbFlsRVhBVVg0MlZNQVpRV1l4Z29vSW1LUUt6aDBxUwpyZWRzcmUyOiQyeSQwNSRyc1BtVUhKd0lNTG95Z1Q3bEtZUVVPWGdqTUdmRUVQZ1BvaVVOc3Jxek16a1RzNDVsbkpoUwpibHVldmlld2VyMTokMnkkMDUkbmRFM0JibkFmb0NaSFJrTEhhR3V1ZU1zOGkwR052aXFXaTZEQ2tqNDVENEo1ZHRnZzdiRnkKYmx1ZXZpZXdlcjI6JDJ5JDA1JGMuVTJhdEhHU0RMcGhjdlNiT0dxS09vbXBqdXpaZkgwY0VISXFkZDR0SkVjOFUyTmhhMHpTCnJlZHZpZXdlcjE6JDJ5JDA1JEt0cUg2RVNKeFB3QU5GbVo0bzFoeS5hcGFabUFGN21sSkRVUkg1RHBOWUVLNFRlNFFqZS9lCnJlZHZpZXdlcjI6JDJ5JDA1JGozTS51VFZjRGRBcGt0LlFkRkl3b09nV0lFcm9FS3lhYkM2Snh2NWRlUUVBdkx0NlIxeTh5CmFjbXNyZTE6JDJ5JDA1JHB0b1NkWUFRZWp0WmFEOUs2cGQ2ak95TjhOZlFoWklmbmp5MnZFcHhpL1lzT0kyNk1LbHJ1CmFjbXNyZTI6JDJ5JDA1JGNsa1JjTHlySU5IQ3Joc3gvNEVYOE9LZnBYQTZraXFaZ3lSREZ3c0xpSnptdlVLMEdER3pDCmFjbXZpZXdlcjE6JDJ5JDA1JHIxVmpDZnptTTZGamtMYnVucWxYRU9ZVWUvb3JZN3U3QUxTNUlxV0tVNldiSHpZaHlWaGhlCmFjbXZpZXdlcjI6JDJ5JDA1JGY4RXpOZ09VdW1KUmtUQm90WlRHYXVXWmlIL1FYT0RsT1RwQ2dMMlNlNEEyVHlGQ2ZSSmRlCg==
type: Opaque

