apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: kyverno-placement
  namespace: kyverno-policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["redteam","blueteam"]}

