apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policies
  namespace: policies
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        requeueAfterSeconds: 30
        labelSelector:
          matchLabels:              # OPTIONAL
            cluster.open-cluster-management.io/placement: policies
  template: 
    # This is a template Argo CD Application, but with support for parameter substitution.
    metadata:
      name: 'policies'
    spec:
      project: "policies"
      source:
        repoURL: https://github.com/ch-stark/application-set-deploy-policies
        targetRevision: main
        path: deploy
      destination:
        server: '{{server}}'
        namespace: policies
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=orphan


